/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "jni_func.h"
/* Header for class android_serialport_api_SerialPort */

#ifndef _Included_android_serialport_api_SerialPort
#define _Included_android_serialport_api_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     android_serialport_api_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;II)Ljava/io/FileDescriptor;
 */
JNIEXPORT jobject JNICALL MAKE_JNI_FUNC_NAME_FOR_SerialPort(open)
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     android_serialport_api_SerialPort
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL MAKE_JNI_FUNC_NAME_FOR_SerialPort(close)
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
